### Домашнее задание 1
---

Импорт библиотеки NumPy с общепринятым сокращением

In [1]:
import numpy as np

Примеры создания массивов

In [2]:
a = np.array([1, 2, 3, 4, 5]) # Создание массива из обычного списка
a

array([1, 2, 3, 4, 5])

In [8]:
a_zeros = np.zeros(5) # Содание одномерного массива функцией zeros
a_ones = np.ones((3, 2)) # Создание двумерного массива функцией ones
a_arange = np.arange(1, 6, 2) # Создание массива функцией arange
print(a_zeros)
print(a_ones)
print(a_arange)

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1 3 5]


Демонстрация атрибутов

In [9]:
print(a_ones.shape) # размер массива с единицами
print(a_ones.dtype) # тип данных элементов массива

(3, 2)
float64


Примеры индексирования и срезов

In [20]:
number_1 = a_arange[1] # получаем второй элемент из одномерного массива
print(number_1)

number_2 = a_ones[2, 1] # индексация элемента на третьей строке и втором столбце
print(number_2)

3
1.0


In [ ]:
slice_1 = a[1:3] # срез массива со 2 (включительно) по 4 (не включительно) элемент
print(slice_1)

slice_2 = a_ones[1:3, 0:1] # срез двумерного массива: 2 и 3 строка, 1-ый столбец
print(slice_2)

[2 3]
[[1.]
 [1.]]


Примеры векторных операций и базовых статистик

In [23]:
a = np.array([1, 2, 5, 3, 9])
b = np.array([5, 2, 1, 0, 4])
print(a + b) # сложение массивов по элементно
print(a * 2) # умножение каждого элемента массива на 2

[ 6  4  6  3 13]
[ 2  4 10  6 18]


In [26]:
mean_a = np.mean(a) # среднее значение массива a
max_a = np.max(a) # максимальное значение массива a
min_a = np.min(a) # минимальное значение массива a
print(min_a, mean_a, max_a)

1 4.0 9
